---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPSMAN_ENV_FILE_NAME:
  CONFIG_FILE_NAME:

inputs:
- name: pipelines-repo
- name: om-cli
- name: jq
- name: config
- name: env

run:
  path: pipelines-repo/tasks/apply-changes/task.sh
