---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  CI_USERNAME:
  CI_EMAIL_ADDRESS:

inputs:
  - name: pipelines-repo
  - name: concourse-trigger-gist

outputs:
  - name: updated-concourse-trigger-gist

run:
  path: pipelines-repo/tasks/gist-update/task.sh
