---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPSMAN_ENV_FILE_NAME:

inputs:
- name: pipelines-repo
- name: om-cli
- name: env
- name: stemcells

run:
  path: pipelines-repo/tasks/upload-stemcell/task.sh
