resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pipelines-repo
  type: git
  source:
    uri: ((github_repo))
    branch: ((github_branch))
    username: ((github_username))
    password: ((github_token))

jobs:

- name: pause-install-pipeline
  plan:
  - aggregate:
    - get: pipelines-repo

  - task: apply-changes
    file: pipelines-repo/tasks/change-pipeline-state/task.yml
    params:
      DEBUG: ((debug))
      CONCOURSE_USERNAME: ((concourse_username))
      CONCOURSE_PASSWD: ((concourse_passwd))
      ATC_EXTERNAL_URL: ((atc_external_url))
      PIPELINE_NAME: ((pipeline_name))
      TEAM_NAME: ((team_name))
      PIPELINE_STATE: ((pipeline_state))
