---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPSMAN_ENV_FILE_NAME:
  PRODUCT_NAME:

inputs:
- name: pipelines-repo
- name: om-cli
- name: jq
- name: tile-config-convertor
- name: env

run:
  path: pipelines-repo/tasks/generate-config/task.sh
