---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  CF_API_ENDPOINT:
  CF_USER:
  CF_PASSWORD:
  BUILDPACK_NAME:
  BUILDPACK_POSITION:
  ORG:
  SPACE:
  IS_ENABLE:

inputs:
  - name: pivnet-product
  - name: pipelines-repo
  - name: cf-cli

run:
  path: pipelines-repo/tasks/update-buildpack/task.sh
